# Generated by Django 4.2.2 on 2023-06-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminformation',
            name='rating_change',
            field=models.IntegerField(default=0),
        ),
    ]
