# Generated by Django 4.2.2 on 2023-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjudgestats', '0002_alter_recentstandings_penalty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VjudgeStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='recentStandings',
        ),
    ]
